### Library to clean/organize/standardize data
{
library(readr)
library(dplyr)
library(tidyr)
library(data.table)
library(plyr)
library(stringi)
library(tm)
library(readxl) 
library(stringr) 
library(tidyverse)
library(DescTools)
}
### Library to analyze section
library(readr)
library(tidyverse)
library(stargazer)
library(ggplot2)
library(data.table)
library(viridis)
library(xtable)
library(stargazer)
library(plm)
library(lmtest)
