### RAW DATA ###
### 702 Firms and 56160 observations
### Variables deflated with IPCA IBGE ACUMUL - 14/07/2020
### Variables NOT deflated: EBIT_POR_DESPFIN_LIQ e EBIT_POR_DESPFIN_BRUT
### Firms with open capital, traded in Bovespa

### VARIABLES DEFINITION
# AT = ATIVO TOTAL
# K = IMOBILIZADO
# LL = LUCRO LÍQUIDO
# D_CP = PASSIVO CIRCULANTE
# D_LP = PASSIVO NÃO CIRCULANTE
# V = VENDAS (RECEITA OPERACIONAL LÍQUIDA)
# DEP_1 = DEPRECIAÇÃO (DOAR)
# DEP_2 = DEPRECIAÇÃO (FLUXO DE CAIXA)
# DEP_3 = DEPRECIAÇÃO E AMORTIZAÇÃO (INDICADOR ECONOMÁTICA) - GRANDE VARIAÇÃO EM RELAÇÃO A DEP_2
# CAIXA_EQ = CAIXA E EQUIVALANTES (FLUXO DE CAIXA)
# CAIXA_DISP = CAIXA (DISPONÍVEL E INVESTIMENTOS DE CURTO PRAZO)
# DIV_PAGOS = DIVIDENDOS PAGOS (FLUXO DE CAIXA)
# QTD_AÇÕES = QUANTIDADE DE AÇÕES
# DIVIDENDOS = GASTOS COM DIVIDENDOS (DOAR)
# DIV_YIELD = DIVIDEND YIELD (INDICADOR ECONOMÁTICA)
# DIV_POR_AÇÃO = DIVIDENDO POR AÇÃO (INDICADOR ECONOMÁTICA)
# PL = PATRIMÔNIO LÍQUIDO
# V_MERC = VALOR DE MERCADO (INDICADOR ECONOMÁTICA)
# DESP_FIN = DESPESAS FINANCEIRAS (DRE)
# LUC_OP1 = LUCRO OPERACIONAL (DRE)
# LUC_OP2 = LUCRO OPERACIONAL (ANTIGO) (DRE)
# EBIT = LUCRO ANTES DE JUROS E IMPOSTOS EBIT (DRE)
# EBIT_POR_DESPFIN_LIQ = INDICADOR ECONOMÁTICA
# EBIT_POR_DESPFIN_BRUT = INDICADOR ECONOMÁTICA
# PRECO_FECHAMENTO = PREÇO DA AÇÃO (FECHAMENTO)


### CLEANED DATA ###
### 284 FIRMS AND 10079 OBSERVATIONS
### first observations starts at 2006

### VARIABLES DEFINITION
# DEP = DEP_2
# CAIXA = JOIN FROM CAIXA_EQ AND CAIXA_DISP
# DIV_PAGOS = DIVIDENDOS PAGOS (FLUXO DE CAIXA)
# AGE = DATA DE CONSTITUIÇÃO CVM